### ISSUE TITLE
Edit (or at least allow to view) email templates

### ISSUE THREAD

**Issue by idengager** [LunarLogic/rails-girls-submissions#131]
Would be cool to know what kind of words you're actually sending to other human beings.

**Comment by ravicious** [comment]
Is there a gem that implements that? I wouldn't want to spend too much time on this, especially since after we implement #129 we will be sending only two emails through the app which can be seen under `app/views/invitations_mailer`.

**Comment by ravicious** [comment]
Closing this since we can implement #129 instead and as I said, see exactly what we send just by looking at the template.
