### ISSUE TITLE
Automate checking Codecademy progress

### ISSUE THREAD

**Issue by idengager** [LunarLogic/rails-girls-submissions#132]
It's a pain in the neck to validate Codecademy progress manually. Common issues include:
- applicants put in wrong username (it is described clear enough what we want from them?)
- it's easy to click the wrong button to confirm completed/not completed status on the application page

Many applicants don't make any progress at all on Codecademy, or very little – it might be instructive to research that first.

**Comment by ravicious** [comment]
Let's research if they have some kind of an API for that, I wouldn't want to scrap this data from their website (because we need this just once a year and it can easily break due to website changes next year). Or we could implement scraping just before the next edition.

**Comment by ravicious** [comment]
Closing this as we want to get rid of CodeCademy (#137).
