### ISSUE TITLE
The form closes one day earlier than expected

### ISSUE THREAD

**Issue by szynszyliszys** [LunarLogic/rails-girls-submissions#133]
If we set a date of ending the registration for the May 1st, the form closes on April 30th (we expect the form to close at May 1st 23:59:59 or one second later ;)).

**Comment by ravicious** [comment]
Also, it would be nice to include the exact time the form closes as a countdown on the page so that people don't have to guess whether "the form closes on May 1st" means May 1st 23:59 or April 30th 23:59.
