### ISSUE TITLE
Review priorities for RG Krk 2019

### ISSUE THREAD

**Issue by idengager** [LunarLogic/rails-girls-submissions#140]

**Comment by idengager** [comment]
@ravicious Would you assign me for this one?

**Comment by ravicious** [comment]
Actually, I want to do this too, I was thinking about using this value vs effort matrix here to take on the biggest tasks first. We can probably also use GitHub Projects and create a board in order to prioritize the work.

**Comment by ravicious** [comment]
I created [a project](https://github.com/LunarLogic/rails-girls-submissions/projects/1) and prioritized stuff there according to the my effort-value matrix that (see below).

https://www.mindtheproduct.com/2017/07/enter-matrix-lean-prioritisation/

![](https://3lsqjy1sj7i027fcn749gutj-wpengine.netdna-ssl.com/wp-content/uploads/2017/07/Picture5.png)

My matrix:

![value-effort-rgk](https://user-images.githubusercontent.com/27113/53658946-7ccc5580-3c5a-11e9-80b1-fe9742c1ab92.png)

**Comment by idengager** [comment]
I agree with the order you're arrived at. Good job 💯 

Fixed.
