### ISSUE TITLE
Update the questions

### ISSUE THREAD

**Issue by ravicious** [LunarLogic/rails-girls-submissions#148]
- [x] Combine HTML & CSS into one question.
- [x] "Let us know your experience level in popular web technologies. We will use this info to assign you to the group in which you can learn the most. Don't worry if all of this sounds unfamiliar, beginners are perfect candidates for the workshop."
- [x] Don't capitalize "Basic" and "Fluent" answers for English level.
- [x] "Is there anything we should be aware of to make your experience during the workshop better? For example: your dietary restrictions, allergies, child care for the time of the event, any other kind of assistance. We're dedicated to making our workshop available to everyone."
- [x] "Your gender self-identification" text field over age.
- [x] Change age to "I'm over 18 years old".

**Comment by Sonje** [comment]
- [ ] Radio buttons are a bit off (to the top) - not in line with text, can we change that?
- [ ] Graphics and dates need updating

**Comment by ravicious** [comment]
@Sonje Yeah, I forgot to mention that the dates will be updated to reflect the real event. When it comes to graphics, AFAIK we're going to keep the current ones, unless you mean something else than the drawing at the top of the page?

And I see you're returning the favor with the radio buttons alignment. 😄

**Comment by Sonje** [comment]
Yeah, I thought about the drawing at the top. If we keep it, it's fine with me :)

**Comment by ravicious** [comment]
The issue with radio buttons seems to stem from the fact that we're not setting the font size specifically anywhere and we're using default browser styles. Adding flexbox to the div with the checkbox and the label didn't help, so I'm going to leave it as it is for now.
